name: Generate Snake

on:
  schedule:
    # Corre cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch: # Permite correrlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: jc-caldas23
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
            dist/github-snake.gif

      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
